import = ["~/.config/alacritty/themes/themes/gruvbox_dark.toml"]

[shell]
program = "/bin/zsh"
args = ["--login"]

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.normal]
family = "Iosevka Nerd Font"
style = "Regular"

[[keyboard.bindings]]
key = "K"
mods = "Command"
chars = "\u000b"

[window]
startup_mode = "Maximized"

[window.padding]
x = 8
y = 8
