FROM opensuse/tumbleweed

RUN zypper refresh \
    && zypper install -y sudo \
    && useradd -m -s /bin/zsh heron \
    && echo 'heron ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers \
    && echo 'heron:123' | chpasswd \
    && mkdir -p /home/heron/Workbench /home/heron/.local/bin \
    && chown -R heron:heron /home/heron \
    && USER heron

COPY --chown=heron:heron ./ /home/heron/Workbench/dotfiles
WORKDIR /home/heron/Workbench/dotfiles

RUN chmod +x ./bootstrap && ./bootstrap

CMD ["/bin/zsh"]
