FROM ubuntu:rolling

RUN apt update && apt install -y sudo \
    && useradd -m -s /bin/zsh heron \
    && usermod -aG sudo heron \
    && echo 'heron ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers \
    && echo 'heron:123' | chpasswd

USER heron

COPY --chown=heron:heron ./ /home/heron/Workbench/dotfiles
WORKDIR /home/heron/Workbench/dotfiles

RUN chmod +x ./bootstrap && ./bootstrap

CMD ["/bin/zsh"]
