[terminal.shell]
program = "/bin/zsh"
args = ["--login"]

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.normal]
family = "Iosevka Nerd Font Mono"
style = "Regular"
# style = "Thin"

# [[keyboard.bindings]]
# key = "K"
# mods = "Command"
# chars = "\u000b"

[window]
startup_mode = "Maximized"
option_as_alt = "Both"
# decorations = 'none'
dynamic_title = true
blur = true
opacity = 1

[window.padding]
x = 8
y = 8

[general]
import = [
  # "~/.config/alacritty/themes/themes/gruvbox_light.toml",
  # "~/.config/alacritty/themes/themes/gruvbox_dark.toml",
  # "~/.config/alacritty/themes/themes/catppuccin_frappe.toml",
  "~/.config/alacritty/themes/themes/nord.toml",
  # "~/.config/alacritty/themes/themes/solarized_dark.toml",
  # "~/.config/alacritty/themes/themes/solarized_light.toml",
  # "~/.config/alacritty/themes/themes/nordic.toml",
  # "~/.config/alacritty/themes/themes/dracula.toml",
  # "~/.config/alacritty/themes/themes/monokai.toml",
  # "~/.config/alacritty/themes/themes/rose_pine_moon.toml",
  # "~/.config/alacritty/themes/themes/",
]

# Copy
# [[keyboard.bindings]]
# key = "C"
# mods= "Control"
# chars= "\\x03"
[[keyboard.bindings]]
key = "C"
mods = "Command"
action = "Copy"

# Paste
# [[keyboard.bindings]]
# key = "V"
# mods= "Control"
# chars= "\u0026"
[[keyboard.bindings]]
key = "V"
mods = "Command"
action = "Paste"

# Quit
[[keyboard.bindings]]
key = "Q"
mods = "Control"
chars = "\u0021"

# New Tab
# [[keyboard.bindings]]
# key = "T"
# mods = "Control"
# chars = "\u0024"

# Close Tab
[[keyboard.bindings]]
key = "W"
mods = "Control"
chars = "\u0027"

# Next Tab
# [[keyboard.bindings]]
# key = "Tab"
# mods = "Control"
# chars = "\u0011"

# Previous Tab
# [[keyboard.bindings]]
# key = "Tab"
# mods = "Control | Shift"
# chars = "\u0011"

# Clear Scrollback
[[keyboard.bindings]]
key = "K"
mods = "Control"
chars = "\u0013"

# Command + backspace to delete entire line
[[keyboard.bindings]]
key = "Back"
mods = "Command"
chars = "\u0015"

# Command + left arrow to move to the beginning of the line
[[keyboard.bindings]]
key = "ArrowLeft"
mods = "Command"
chars = "\u0001"
# Command + right arrow to move to the end of the line
[[keyboard.bindings]]
key = "ArrowRight"
mods = "Command"
chars = "\u0005"
# With Home & End keys
[[keyboard.bindings]]
key = "Home"
chars = "\u0001"
[[keyboard.bindings]]
key = "End"
chars = "\u0005"

# Option + arrows to move by word
[[keyboard.bindings]]
key = "ArrowLeft"
mods = "Option"
chars = "\u001BB"
# action = "SemanticLeft"
[[keyboard.bindings]]
key = "ArrowRight"
mods = "Option"
chars = "\u001BF"
# action = "SemanticRight"

[[keyboard.bindings]]
key = "Left"
mods = "Command"
chars = "\u001BOH" # Cmd + Left → Move to line start

[[keyboard.bindings]]
key = "Right"
mods = "Command"
chars = "\u001BOF" # Cmd + Right → Move to line end

# [[keyboard.bindings]]
# key = "Left"
# mods = "Alt"
# chars = "\u001Bb" # Option + Left → Move back one word

# [[keyboard.bindings]]
# key = "Right"
# mods = "Alt"
# chars = "\u001Bf" # Option + Right → Move forward one word

# Scroll up/down (Cmd + Up/Down)
# (For when you don't have a mouse/trackpad)
[[keyboard.bindings]]
key = "Up"
mods = "Command"
action = "ScrollPageUp"

[[keyboard.bindings]]
key = "Down"
mods = "Command"
action = "ScrollPageDown"

# Delete word backward (Option + Backspace) toml
[[keyboard.bindings]]
key = "Back"
mods = "Alt"
chars = "\u0017" # Ctrl+W (Delete previous word)

# Split Pane (Cmd + D, like tmux)
# (Requires tmux running)
[[keyboard.bindings]]
key = "D"
mods = "Command"
chars = "\u0002%" # Sends Ctrl+B % (tmux horizontal split)

# [[keyboard.bindings]]
# key = "T"
# mods = "Control"
# action = "CreateNewTab"

# Tabs navigation
[[keyboard.bindings]]
key = "Tab"
mods = "Control"
action = "SelectNextTab"
[[keyboard.bindings]]
key = "Tab"
mods = "Control|Shift"
action = "SelectPreviousTab"
# Switch tabs (Cmd + Shift + [ / ])
# (For when using tmux or Zellij)
[[keyboard.bindings]]
key = "LBracket"
mods = "Command|Shift"
chars = "\u0002p"      # Ctrl+B p (previous tab in tmux)
[[keyboard.bindings]]
key = "RBracket"
mods = "Command|Shift"
chars = "\u0002n"      # Ctrl+B n (next tab in tmux)

# Fast Pane Navigation (tmux + Alacritty)
# [[keyboard.bindings]]
# key = "H"
# mods = "Command"
# chars = "\u0002h"  # Move left
# [[keyboard.bindings]]
# key = "L"
# mods = "Command"
# chars = "\u0002l"  # Move right
# [[keyboard.bindings]]
# key = "J"
# mods = "Command"
# chars = "\u0002j"  # Move down
# [[keyboard.bindings]]
# key = "K"
# mods = "Command"
# chars = "\u0002k"  # Move up
